name: Build Project

on:
  push:
    branches:
      - '**'
    tags:
      - '*'
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle
      - name: Build with Gradle
        run: ./gradlew build
      - name: Upload to Discord (If pre-release tag)
        if: "startsWith(github.ref, 'refs/tags/') && endsWith(github.ref, '-[0-9]+')"
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        run: ./gradlew discordupload
      - name: Publish to Curseforge (If release tag)
        if: "startsWith(github.ref, 'refs/tags/') && !endsWith(github.ref, '-[0-9]+')"
        env:
          CURSE_API: ${{ secrets.CURSE_API }}
        run: ./gradlew curseforge
      - uses: shallwefootball/s3-upload-action@master
        with:
          if: "startsWith(github.ref, 'refs/tags/') && !endsWith(github.ref, '-[0-9]+')"
          aws_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
          aws_bucket: ${{ secrets.AWS_BUCKET }}
          source_dir: 'docs/forgeupdatefile'
          destination_dir: 'modversions'
